#!/bin/bash
# postrm script for astroberry-server-wui

# disable astroberry site
if [ "$1" = "remove" -o "$1" = "purge" ] && [ -e /etc/nginx/sites-enabled/astroberry ]; then
    rm -f /etc/nginx/sites-enabled/astroberry
fi

if [ "$1" = "remove" -o "$1" = "purge" ] && [ -e /etc/nginx/sites-enabled/astroberry_ssl ]
then
    rm -f /etc/nginx/sites-enabled/astroberry_ssl
fi

# reactivate default site for nginx
if [ "$1" = "remove" -o "$1" = "purge" ] && [ -e /etc/nginx/sites-available/default ] && [ ! -e /etc/nginx/sites-enabled/default ]
then
    ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
fi

# remove astroberry version file
if [ "$1" = "remove" -o "$1" = "purge" ] && [ -e /var/www/html/version.html ]; then
    rm -f /var/www/html/version.html
fi

if [ "$1" = "remove" -o "$1" = "purge" ]
then
	systemctl restart nginx.service
fi

if [ "$1" = "upgrade" ]
then
        systemctl restart gpspanel.service
        systemctl restart astropanel.service
        systemctl restart indiwebmanager.service
        systemctl restart novnc.service
	systemctl restart nginx.service
fi
