#!/bin/bash
# prerm script for astroberry-server-wui

if [ "$1" = "remove" -o "$1" = "purge" ]
then
        systemctl stop gpspanel.service && systemctl disable gpspanel.service
        systemctl stop astropanel.service && systemctl disable astropanel.service
        systemctl stop indiwebmanager.service && systemctl disable indiwebmanager.service
        systemctl stop novnc.service && systemctl disable novnc.service
fi
