#!/bin/bash
# postrm script for astroberry-server-wui

# Disable astroberry services
systemctl stop gpspanel.service && systemctl disable gpspanel.service
systemctl stop astropanel.service && systemctl disable astropanel.service
systemctl stop indiwebmanager.service && systemctl disable indiwebmanager.service
systemctl stop novnc.service && systemctl disable novnc.service

